package fr.nate.anonymizer.io;

import java.io.BufferedReader;
import java.io.IOException;

/**
 * An interface defining a provider for input and output.
 * It provides an input to the user and an output file or
 * handler, automatically generated by the provider.
 */
public interface IoProvider {

    /**
     * Fetches a BufferedReader on the next input available.
     * @return a BufferedReader on the next input available.
     * @throws IOException In case of an IO error.
     */
    BufferedReader nextReader() throws IOException;

    /**
     * Writes a string to the output return corresponding to the
     * currently used input.
     * @param line The string to be written to the output return.
     * @throws IOException In case of an IO error.
     */
    void writeReturn(String line) throws IOException;

    /**
     * Closes the current output return handle.
     * This is called by the nextReader method automatically.
     * @throws IOException In case of an IO error.
     */
    void closeReturnWriter() throws IOException;

}
